# Site settings
title: Gena Example Blog
email: hello@60devs.com
description:
url: "http://60devs.github.io/gena-blog" # the base hostname & protocol for your site
twitter_username: "60devs"
github_username: "60devs"
permalink: /:title.html
deploy:
  method: 'github'
  url: 'git@github.com:60devs/gena-blog.git'
  branch: 'gh-pages'
sitemap:
  changefreq: weekly
pages_order:
  - blog
  - about
build:
  - handlebars
  - public
  - styles
  - js
  - sitemap
  - rss
dev-build:
  - handlebars
  - public
  - styles-lite
  - dev-js
highlightjs_root: 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.4/'
